baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TIMEZONE4'
theme = 'm10c'

[params]
  author = "Thomas Elsgaard"
  description = "Accept that other people and groups want to choose their own path, just as you do, and don’t worry too much if you can’t get them to see things your way."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/elsgaard"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/telsgaard"
  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://linkedin.com/elsgaard"
