baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Parting the Clouds, Seeking the Way with Elsgaard'
theme = 'm10c'

[params]
  author = "Thomas Elsgaard"
  description = "A blog about Go and Site Reliability Engineering."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/elsgaard"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/telsgaard"
