baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Thomas Elsgaard'
theme = 'm10c'

[params]
  author = "TIMEZONE4"
  description = "Jeg vil skabe noget fedt, og flytte status quo for hvordan moderne IT-systemer skal være. Hvis du er på udkig efter en standard løsning, er det bedst for alle parter, hvis det ikke er mig, der laver den. For jeg vil lave det, der ikke allerede findes - det er det, jeg er bedst til, og det, jeg synes er sjovt."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/elsgaard"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/telsgaard"
  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://linkedin.com/elsgaard"
